// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.medication;

import eu.wuttke.nrf.domain.medication.AtcCode;
import javax.persistence.Entity;

privileged aspect AtcCode_Roo_Jpa_Entity {
    
    declare @type: AtcCode: @Entity;
    
}
