// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.medication;

import eu.wuttke.nrf.domain.medication.Medication;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Medication_Roo_Configurable {
    
    declare @type: Medication: @Configurable;
    
}
