// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.medication;

import eu.wuttke.nrf.domain.medication.PharmaceuticalForm;

privileged aspect PharmaceuticalForm_Roo_JavaBean {
    
    public String PharmaceuticalForm.getShortcut() {
        return this.shortcut;
    }
    
    public void PharmaceuticalForm.setShortcut(String shortcut) {
        this.shortcut = shortcut;
    }
    
    public String PharmaceuticalForm.getName() {
        return this.name;
    }
    
    public void PharmaceuticalForm.setName(String name) {
        this.name = name;
    }
    
}
