// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.medication;

import eu.wuttke.nrf.domain.medication.PharmaceuticalForm;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PharmaceuticalForm_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager PharmaceuticalForm.entityManager;
    
    public static final EntityManager PharmaceuticalForm.entityManager() {
        EntityManager em = new PharmaceuticalForm().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long PharmaceuticalForm.countPharmaceuticalForms() {
        return entityManager().createQuery("SELECT COUNT(o) FROM PharmaceuticalForm o", Long.class).getSingleResult();
    }
    
    public static List<PharmaceuticalForm> PharmaceuticalForm.findAllPharmaceuticalForms() {
        return entityManager().createQuery("SELECT o FROM PharmaceuticalForm o", PharmaceuticalForm.class).getResultList();
    }
    
    public static PharmaceuticalForm PharmaceuticalForm.findPharmaceuticalForm(String shortcut) {
        if (shortcut == null || shortcut.length() == 0) return null;
        return entityManager().find(PharmaceuticalForm.class, shortcut);
    }
    
    public static List<PharmaceuticalForm> PharmaceuticalForm.findPharmaceuticalFormEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM PharmaceuticalForm o", PharmaceuticalForm.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void PharmaceuticalForm.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void PharmaceuticalForm.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            PharmaceuticalForm attached = PharmaceuticalForm.findPharmaceuticalForm(this.shortcut);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void PharmaceuticalForm.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void PharmaceuticalForm.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public PharmaceuticalForm PharmaceuticalForm.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        PharmaceuticalForm merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
