// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.medication;

import eu.wuttke.nrf.domain.medication.Substance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Substance_Roo_Configurable {
    
    declare @type: Substance: @Configurable;
    
}
