package eu.wuttke.nrf.ui.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class SearchListComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayoutFooter;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnOk;
	@AutoGenerated
	private Table tableSearchResult;
	@AutoGenerated
	private HorizontalLayout horizontalLayoutHeader;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private TextField tfSearch;
	@AutoGenerated
	private Label lblSearch;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchListComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayoutHeader
		horizontalLayoutHeader = buildHorizontalLayoutHeader();
		mainLayout.addComponent(horizontalLayoutHeader);
		
		// tableSearchResult
		tableSearchResult = new Table();
		tableSearchResult.setImmediate(false);
		tableSearchResult.setWidth("100.0%");
		tableSearchResult.setHeight("100.0%");
		mainLayout.addComponent(tableSearchResult);
		mainLayout.setExpandRatio(tableSearchResult, 1.0f);
		
		// horizontalLayoutFooter
		horizontalLayoutFooter = buildHorizontalLayoutFooter();
		mainLayout.addComponent(horizontalLayoutFooter);
		mainLayout.setComponentAlignment(horizontalLayoutFooter, new Alignment(
				6));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutHeader() {
		// common part: create layout
		horizontalLayoutHeader = new HorizontalLayout();
		horizontalLayoutHeader.setImmediate(false);
		horizontalLayoutHeader.setWidth("100.0%");
		horizontalLayoutHeader.setHeight("-1px");
		horizontalLayoutHeader.setMargin(false);
		horizontalLayoutHeader.setSpacing(true);
		
		// lblSearch
		lblSearch = new Label();
		lblSearch.setImmediate(false);
		lblSearch.setWidth("-1px");
		lblSearch.setHeight("-1px");
		lblSearch.setValue("Search");
		horizontalLayoutHeader.addComponent(lblSearch);
		horizontalLayoutHeader.setComponentAlignment(lblSearch, new Alignment(
				33));
		
		// tfSearch
		tfSearch = new TextField();
		tfSearch.setImmediate(false);
		tfSearch.setWidth("100.0%");
		tfSearch.setHeight("-1px");
		horizontalLayoutHeader.addComponent(tfSearch);
		horizontalLayoutHeader.setExpandRatio(tfSearch, 1.0f);
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setCaption("Search");
		btnSearch.setImmediate(true);
		btnSearch.setWidth("-1px");
		btnSearch.setHeight("-1px");
		horizontalLayoutHeader.addComponent(btnSearch);
		horizontalLayoutHeader.setComponentAlignment(btnSearch, new Alignment(
				34));
		
		return horizontalLayoutHeader;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutFooter() {
		// common part: create layout
		horizontalLayoutFooter = new HorizontalLayout();
		horizontalLayoutFooter.setImmediate(false);
		horizontalLayoutFooter.setWidth("-1px");
		horizontalLayoutFooter.setHeight("-1px");
		horizontalLayoutFooter.setMargin(false);
		horizontalLayoutFooter.setSpacing(true);
		
		// btnOk
		btnOk = new Button();
		btnOk.setCaption("OK");
		btnOk.setImmediate(true);
		btnOk.setWidth("80px");
		btnOk.setHeight("-1px");
		horizontalLayoutFooter.addComponent(btnOk);
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Cancel");
		btnCancel.setImmediate(true);
		btnCancel.setWidth("80px");
		btnCancel.setHeight("-1px");
		horizontalLayoutFooter.addComponent(btnCancel);
		
		return horizontalLayoutFooter;
	}

	private static final long serialVersionUID = 1L;

}
