package eu.wuttke.nrf.ui.visit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.PropertyId;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import eu.wuttke.nrf.domain.visit.Visit;
import eu.wuttke.nrf.ui.misc.StringToDateTimeConverter;
import eu.wuttke.nrf.ui.view.EditorView;

public class VisitEditorView 
extends CustomComponent
implements EditorView<Visit> {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private FormLayout formLayout;
	@AutoGenerated
	@PropertyId("visitDateTime")
	private TextField tfVisitDateTime;
	@AutoGenerated
	@PropertyId("label")
	private TextField tfLabel;
	private static final long serialVersionUID = 1L;
	
	private BeanItem<Visit> beanItem;
	private FieldGroup group;

	public VisitEditorView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		tfVisitDateTime.setConverter(new StringToDateTimeConverter());
	}
	
	@Override
	public void displayEntity(Visit d) {
		beanItem = new BeanItem<Visit>(d);
		group = new FieldGroup(beanItem);
		group.bindMemberFields(this);
	}

	@Override
	public Visit retrieveValidatedEntity() {
		try {
			group.commit();
			return beanItem.getBean();
		} catch (CommitException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	@Override
	public boolean isValid() {
		return group.isValid();
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// formLayout
		formLayout = buildFormLayout();
		mainLayout.addComponent(formLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private FormLayout buildFormLayout() {
		// common part: create layout
		formLayout = new FormLayout();
		formLayout.setImmediate(false);
		formLayout.setWidth("100.0%");
		formLayout.setHeight("100.0%");
		formLayout.setMargin(false);
		formLayout.setSpacing(true);
		
		// tfLabel
		tfLabel = new TextField();
		tfLabel.setCaption("Label");
		tfLabel.setImmediate(false);
		tfLabel.setWidth("100.0%");
		tfLabel.setHeight("-1px");
		tfLabel.setRequired(true);
		formLayout.addComponent(tfLabel);
		
		// tfValidFrom
		tfVisitDateTime = new TextField();
		tfVisitDateTime.setCaption("Date Time");
		tfVisitDateTime.setImmediate(true);
		tfVisitDateTime.setWidth("100.0%");
		tfVisitDateTime.setHeight("-1px");
		tfVisitDateTime.setRequired(true);
		formLayout.addComponent(tfVisitDateTime);
		
		return formLayout;
	}

}
