package eu.wuttke.nrf.ui.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class EditableListComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayoutFooter;
	@AutoGenerated
	private Button btnDelete;
	@AutoGenerated
	private Button btnEdit;
	@AutoGenerated
	private Button btnNew;
	@AutoGenerated
	private Table table;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EditableListComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table
		table = new Table();
		table.setImmediate(false);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		mainLayout.addComponent(table);
		mainLayout.setExpandRatio(table, 1.0f);
		
		// horizontalLayoutFooter
		horizontalLayoutFooter = buildHorizontalLayoutFooter();
		mainLayout.addComponent(horizontalLayoutFooter);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutFooter() {
		// common part: create layout
		horizontalLayoutFooter = new HorizontalLayout();
		horizontalLayoutFooter.setImmediate(false);
		horizontalLayoutFooter.setWidth("-1px");
		horizontalLayoutFooter.setHeight("-1px");
		horizontalLayoutFooter.setMargin(false);
		horizontalLayoutFooter.setSpacing(true);
		
		// btnNew
		btnNew = new Button();
		btnNew.setCaption("New");
		btnNew.setImmediate(true);
		btnNew.setWidth("80px");
		btnNew.setHeight("-1px");
		horizontalLayoutFooter.addComponent(btnNew);
		
		// btnEdit
		btnEdit = new Button();
		btnEdit.setCaption("Edit");
		btnEdit.setImmediate(true);
		btnEdit.setWidth("80px");
		btnEdit.setHeight("-1px");
		horizontalLayoutFooter.addComponent(btnEdit);
		
		// btnDelete
		btnDelete = new Button();
		btnDelete.setCaption("Delete");
		btnDelete.setImmediate(false);
		btnDelete.setWidth("80px");
		btnDelete.setHeight("-1px");
		horizontalLayoutFooter.addComponent(btnDelete);
		
		return horizontalLayoutFooter;
	}

}
