package eu.wuttke.nrf.ui.sample;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.PropertyId;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import eu.wuttke.nrf.domain.sample.Sample;
import eu.wuttke.nrf.domain.sample.SampleType;
import eu.wuttke.nrf.ui.misc.StringToPrecisionDateConverter;
import eu.wuttke.nrf.ui.view.EditorView;

public class SampleEditorView
extends CustomComponent 
implements EditorView<Sample> {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private FormLayout formLayout;
	@AutoGenerated
	@PropertyId("comment")
	private TextArea taComment;
	@AutoGenerated
	@PropertyId("amount")
	private TextField tfAmount;
	@AutoGenerated
	@PropertyId("sampleDate")
	private TextField tfSampleDate;
	@AutoGenerated
	@PropertyId("sampleType")
	private ComboBox cbType;
	@AutoGenerated
	@PropertyId("id")
	private TextField tfSampleId;
	private BeanItem<Sample> beanItem;
	private FieldGroup group;
	
	@Override
	public void displayEntity(Sample s) {
		beanItem = new BeanItem<Sample>(s);
		group = new FieldGroup(beanItem);
		group.bindMemberFields(this);
	}

	@Override
	public Sample retrieveValidatedEntity() {
		try {
			group.commit();
			return beanItem.getBean();
		} catch (CommitException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	@Override
	public boolean isValid() {
		return group.isValid();
	}
	
	private static final long serialVersionUID = 1L;
	
	public SampleEditorView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		cbType.setNullSelectionAllowed(false);
		for (SampleType type : SampleType.values())
			cbType.addItem(type);
		
		tfSampleDate.setConverter(new StringToPrecisionDateConverter());
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// formLayout
		formLayout = buildFormLayout();
		mainLayout.addComponent(formLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private FormLayout buildFormLayout() {
		// common part: create layout
		formLayout = new FormLayout();
		formLayout.setImmediate(false);
		formLayout.setWidth("100.0%");
		formLayout.setHeight("100.0%");
		formLayout.setMargin(false);
		formLayout.setSpacing(true);
		
		// tfSampleId
		tfSampleId = new TextField();
		tfSampleId.setCaption("Sample Id");
		tfSampleId.setImmediate(false);
		tfSampleId.setWidth("100.0%");
		tfSampleId.setHeight("-1px");
		tfSampleId.setRequired(true);
		tfSampleId.setNullSettingAllowed(true);
		tfSampleId.setNullRepresentation("");
		formLayout.addComponent(tfSampleId);
		
		// cbType
		cbType = new ComboBox();
		cbType.setCaption("Material");
		cbType.setImmediate(false);
		cbType.setWidth("-1px");
		cbType.setHeight("-1px");
		cbType.setRequired(true);
		formLayout.addComponent(cbType);
		
		// tfSampleDate
		tfSampleDate = new TextField();
		tfSampleDate.setCaption("Sample Date");
		tfSampleDate.setImmediate(false);
		tfSampleDate.setWidth("-1px");
		tfSampleDate.setHeight("-1px");
		tfSampleDate.setNullRepresentation("");
		tfSampleDate.setNullSettingAllowed(true);
		formLayout.addComponent(tfSampleDate);
		
		// tfAmount
		tfAmount = new TextField();
		tfAmount.setCaption("Amount");
		tfAmount.setImmediate(false);
		tfAmount.setWidth("100.0%");
		tfAmount.setHeight("-1px");
		tfAmount.setNullSettingAllowed(true);
		tfAmount.setNullRepresentation("");
		formLayout.addComponent(tfAmount);
		
		// taComment
		taComment = new TextArea();
		taComment.setCaption("Comment");
		taComment.setImmediate(false);
		taComment.setWidth("-1px");
		taComment.setHeight("-1px");
		taComment.setNullSettingAllowed(true);
		taComment.setNullRepresentation("");
		formLayout.addComponent(taComment);
		
		return formLayout;
	}

}
