// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.sample;

import eu.wuttke.nrf.domain.sample.Sample;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Sample_Roo_Configurable {
    
    declare @type: Sample: @Configurable;
    
}
