package eu.wuttke.nrf.ui.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class AdminOverviewView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel;
	@AutoGenerated
	private Panel panelListView;
	@AutoGenerated
	private VerticalLayout verticalLayoutListView;
	@AutoGenerated
	private VerticalLayout verticalLayoutList;
	@AutoGenerated
	private ListSelect listSelectAdmins;
	public AdminOverviewView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		horizontalSplitPanel.setSplitPosition(20f);
		listSelectAdmins.setImmediate(true);
	}
	
	public void displayAdminAreas(String[] areas) {
		for (String area : areas)
			listSelectAdmins.addItem(area);
	}
	
	public void addChosenAdminAreaChangedListener(ValueChangeListener listener) {
		listSelectAdmins.addValueChangeListener(listener);
	}
	
	public void displayListView(Component c) {
		verticalLayoutListView.removeAllComponents();
		if (c != null)
			verticalLayoutListView.addComponent(c);
	}

	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel
		horizontalSplitPanel = buildHorizontalSplitPanel();
		mainLayout.addComponent(horizontalSplitPanel);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel() {
		// common part: create layout
		horizontalSplitPanel = new HorizontalSplitPanel();
		horizontalSplitPanel.setImmediate(false);
		horizontalSplitPanel.setWidth("100.0%");
		horizontalSplitPanel.setHeight("100.0%");
		
		// verticalLayoutList
		verticalLayoutList = buildVerticalLayoutList();
		horizontalSplitPanel.addComponent(verticalLayoutList);
		
		// panelListView
		panelListView = buildPanelListView();
		horizontalSplitPanel.addComponent(panelListView);
		
		return horizontalSplitPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutList() {
		// common part: create layout
		verticalLayoutList = new VerticalLayout();
		verticalLayoutList.setImmediate(false);
		verticalLayoutList.setWidth("100.0%");
		verticalLayoutList.setHeight("100.0%");
		verticalLayoutList.setMargin(true);
		verticalLayoutList.setSpacing(true);
		
		// listSelectAdmins
		listSelectAdmins = new ListSelect();
		listSelectAdmins.setImmediate(false);
		listSelectAdmins.setWidth("100.0%");
		listSelectAdmins.setHeight("-1px");
		verticalLayoutList.addComponent(listSelectAdmins);
		
		return verticalLayoutList;
	}

	@AutoGenerated
	private Panel buildPanelListView() {
		// common part: create layout
		panelListView = new Panel();
		panelListView.setImmediate(false);
		panelListView.setWidth("100.0%");
		panelListView.setHeight("100.0%");
		
		// verticalLayoutListView
		verticalLayoutListView = new VerticalLayout();
		verticalLayoutListView.setImmediate(false);
		verticalLayoutListView.setWidth("100.0%");
		verticalLayoutListView.setHeight("100.0%");
		verticalLayoutListView.setMargin(true);
		verticalLayoutListView.setSpacing(true);
		panelListView.setContent(verticalLayoutListView);
		
		return panelListView;
	}

}
