// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.attachment;

import eu.wuttke.nrf.domain.attachment.AttachmentType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AttachmentType_Roo_Configurable {
    
    declare @type: AttachmentType: @Configurable;
    
}
