package eu.wuttke.nrf.importer;

public enum CystAttributeShortcut {

	 BEZUG_NEUMANNREGISTER_ADPKD,
	
	 PKD1MUTATION_VORHANDEN,
	 PKD2MUTATION_VORHANDEN,
	 KEINE_MUTATION_GEFUNDEN,
	 BEZEICHNUNG_MUTATION,
	
	 STRASSE,
	 PLZ,
	 ORT,
	 LAND,
	 TELEFON,
	 EMAIL,
	 HANDY,
	
	 NACHNAME_HAUSARZT,
	 ORT_HAUSARZT,
	 NACHNAME_NEPHROLOGE,
	 ORT_NEPHROLOGE,

	 CONSENT_JANEIN,
	 HAUSARZT_SOLL_INFORMIERT_WERDEN,
	 NICHT_ANSCHREIBEN,
	 INDEXFALL,
	 VERWANDTE_BEMERKUNG,
	 FAMILIENNAME,
	 FAMILIAERE_ZYSTENNIEREN,
	 BETROFFENE_VERWANDTE_ZAHLEN,
	 BETROFFENE_VERWANDTE_TEXT,
	 
	 NUMMER_ERSTE_PROBE,
	 NUMMER_ZWEITE_PROBE,
	
	 ZYSTENNIERE_RECHTS,
	 ZYSTENNIERE_LINKS,
	 LEBERZYSTEN,
	 SYMPTOMATISCHE_LEBERZYSTEN,
	 ZYSTISCHE_LEBERERKRANKUNG_PLD,
	 PANKREASZYSTEN,
	 MILZZYSTEN,
	 NIERENKARZINOM,
	 ANEURYSMA,
	 ARTERIELLE_HYPERTONIE,
	 HERZKLAPPENFEHLER,
	 HARNWEGSINFEKTE,
	 ANAEMIE,
	 ZEREBROVASKULAERER_INSULT,
	 SIGMADIVERTIKULOSE,
	 NIERENTRANSPLANTATION,
	 DIALYSE,
	 ZN_NEPHREKTOMIE_LINKS,
	 ZN_NEPHREKTOMIE_RECHTS,
	
	 ERSTMANIFESTATION_DATUM,
	 ARTERIELLE_HYPERTONIE_SEIT_DATUM,
	 ZEREBROVASKULAERER_INSULT_DATUM,
	 NEPHREKTOMIE_LINKS_DATUM,
	 NEPHREKTOMIE_RECHTS_DATUM,
	 TEXT_NEPHREKTOMIE_KLINIKBEMERKUNG,
	 ANEURYSMAOPERATION_DATUM,
	 HERZKLAPPENOPERATION_DATUM,
	 NIERENTRANSPLANTATION_DATUM,
	 DIALYSEBEGINN_DATUM,
	
	 EINGABEDATUM,
	 FRAGEBOGEN_AUSGANG,
	 FRAGEBOGEN_EINGANG,
	 ALTER_BEI_ERFASSUNG,
	 LETZTER_AUFENTHALT_UKLFR,
	 DIVERSE_BEMERKUNGEN;

}
