// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.subject;

import eu.wuttke.nrf.domain.subject.Subject;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Subject_Roo_Configurable {
    
    declare @type: Subject: @Configurable;
    
}
