// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.export;

import eu.wuttke.nrf.domain.subject.Gender;
import eu.wuttke.nrf.export.PedFileLine;

privileged aspect PedFileLine_Roo_JavaBean {
    
    public String PedFileLine.getIndividualId() {
        return this.individualId;
    }
    
    public void PedFileLine.setIndividualId(String individualId) {
        this.individualId = individualId;
    }
    
    public String PedFileLine.getFamilyId() {
        return this.familyId;
    }
    
    public void PedFileLine.setFamilyId(String familyId) {
        this.familyId = familyId;
    }
    
    public String PedFileLine.getPaternalId() {
        return this.paternalId;
    }
    
    public void PedFileLine.setPaternalId(String paternalId) {
        this.paternalId = paternalId;
    }
    
    public String PedFileLine.getMaternalId() {
        return this.maternalId;
    }
    
    public void PedFileLine.setMaternalId(String maternalId) {
        this.maternalId = maternalId;
    }
    
    public Gender PedFileLine.getGender() {
        return this.gender;
    }
    
    public void PedFileLine.setGender(Gender gender) {
        this.gender = gender;
    }
    
    public String PedFileLine.getPhenotype() {
        return this.phenotype;
    }
    
    public void PedFileLine.setPhenotype(String phenotype) {
        this.phenotype = phenotype;
    }
    
    public String[] PedFileLine.getGenotypes() {
        return this.genotypes;
    }
    
    public void PedFileLine.setGenotypes(String[] genotypes) {
        this.genotypes = genotypes;
    }
    
}
