// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.encounter;

import eu.wuttke.nrf.domain.encounter.EncounterCategory;
import javax.persistence.Entity;

privileged aspect EncounterCategory_Roo_Jpa_Entity {
    
    declare @type: EncounterCategory: @Entity;
    
}
