// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.event;

import eu.wuttke.nrf.domain.event.EventType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EventType_Roo_Configurable {
    
    declare @type: EventType: @Configurable;
    
}
