package eu.wuttke.nrf.ui.attribute;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class AttributeOverviewView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel;
	@AutoGenerated
	private VerticalLayout verticalLayoutPanelWrapper;
	@AutoGenerated
	private Panel pnlAttributes;
	@AutoGenerated
	private VerticalLayout verticalLayoutAttributes;
	@AutoGenerated
	private VerticalLayout verticalLayoutListWrapper;
	@AutoGenerated
	private HorizontalLayout horizontalLayoutButtonWrapper;
	@AutoGenerated
	private Button btnSync;
	@AutoGenerated
	private Button btnNew;
	@AutoGenerated
	private Table tableVisits;
	public AttributeOverviewView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		horizontalSplitPanel.setSplitPosition(20f, Unit.PERCENTAGE);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel
		horizontalSplitPanel = buildHorizontalSplitPanel();
		mainLayout.addComponent(horizontalSplitPanel);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel() {
		// common part: create layout
		horizontalSplitPanel = new HorizontalSplitPanel();
		horizontalSplitPanel.setImmediate(false);
		horizontalSplitPanel.setWidth("100.0%");
		horizontalSplitPanel.setHeight("100.0%");
		
		// verticalLayoutListWrapper
		verticalLayoutListWrapper = buildVerticalLayoutListWrapper();
		horizontalSplitPanel.addComponent(verticalLayoutListWrapper);
		
		// verticalLayoutPanelWrapper
		verticalLayoutPanelWrapper = buildVerticalLayoutPanelWrapper();
		horizontalSplitPanel.addComponent(verticalLayoutPanelWrapper);
		
		return horizontalSplitPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutListWrapper() {
		// common part: create layout
		verticalLayoutListWrapper = new VerticalLayout();
		verticalLayoutListWrapper.setImmediate(false);
		verticalLayoutListWrapper.setWidth("100.0%");
		verticalLayoutListWrapper.setHeight("100.0%");
		verticalLayoutListWrapper.setMargin(true);
		verticalLayoutListWrapper.setSpacing(true);
		
		// tableVisits
		tableVisits = new Table();
		tableVisits.setImmediate(false);
		tableVisits.setWidth("100.0%");
		tableVisits.setHeight("100.0%");
		verticalLayoutListWrapper.addComponent(tableVisits);
		verticalLayoutListWrapper.setExpandRatio(tableVisits, 1.0f);
		
		// horizontalLayoutButtonWrapper
		horizontalLayoutButtonWrapper = buildHorizontalLayoutButtonWrapper();
		verticalLayoutListWrapper.addComponent(horizontalLayoutButtonWrapper);
		
		return verticalLayoutListWrapper;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutButtonWrapper() {
		// common part: create layout
		horizontalLayoutButtonWrapper = new HorizontalLayout();
		horizontalLayoutButtonWrapper.setImmediate(false);
		horizontalLayoutButtonWrapper.setWidth("-1px");
		horizontalLayoutButtonWrapper.setHeight("-1px");
		horizontalLayoutButtonWrapper.setMargin(false);
		horizontalLayoutButtonWrapper.setSpacing(true);
		
		// btnNew
		btnNew = new Button();
		btnNew.setCaption("New Visit");
		btnNew.setImmediate(true);
		btnNew.setWidth("80px");
		btnNew.setHeight("-1px");
		horizontalLayoutButtonWrapper.addComponent(btnNew);
		
		// btnSync
		btnSync = new Button();
		btnSync.setCaption("KIS Sync");
		btnSync.setImmediate(true);
		btnSync.setWidth("80px");
		btnSync.setHeight("-1px");
		horizontalLayoutButtonWrapper.addComponent(btnSync);
		
		return horizontalLayoutButtonWrapper;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutPanelWrapper() {
		// common part: create layout
		verticalLayoutPanelWrapper = new VerticalLayout();
		verticalLayoutPanelWrapper.setImmediate(false);
		verticalLayoutPanelWrapper.setWidth("100.0%");
		verticalLayoutPanelWrapper.setHeight("100.0%");
		verticalLayoutPanelWrapper.setMargin(true);
		
		// pnlAttributes
		pnlAttributes = buildPnlAttributes();
		verticalLayoutPanelWrapper.addComponent(pnlAttributes);
		
		return verticalLayoutPanelWrapper;
	}

	@AutoGenerated
	private Panel buildPnlAttributes() {
		// common part: create layout
		pnlAttributes = new Panel();
		pnlAttributes.setCaption("Attributes of XXX");
		pnlAttributes.setImmediate(false);
		pnlAttributes.setWidth("100.0%");
		pnlAttributes.setHeight("100.0%");
		
		// verticalLayoutAttributes
		verticalLayoutAttributes = new VerticalLayout();
		verticalLayoutAttributes.setImmediate(false);
		verticalLayoutAttributes.setWidth("100.0%");
		verticalLayoutAttributes.setHeight("100.0%");
		verticalLayoutAttributes.setMargin(false);
		pnlAttributes.setContent(verticalLayoutAttributes);
		
		return pnlAttributes;
	}

}
