package eu.wuttke.nrf.ui.attribute;

import java.util.Collection;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

import eu.wuttke.nrf.domain.attribute.AttributeCategory;
import eu.wuttke.nrf.domain.attribute.AttributeParentType;
import eu.wuttke.nrf.ui.encounter.EncounterListView;

public class AttributeOverviewView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel;

	@AutoGenerated
	private VerticalLayout verticalLayoutPanelWrapper;

	@AutoGenerated
	private HorizontalLayout horizontalLayoutButtons;

	@AutoGenerated
	private Button btnCancel;

	@AutoGenerated
	private Button btnSave;

	@AutoGenerated
	private Panel pnlAttributes;

	@AutoGenerated
	private VerticalLayout verticalLayoutAttributes;

	@AutoGenerated
	private VerticalLayout verticalLayoutListWrapper;

	@AutoGenerated
	private Panel panelAttributeCategories;

	@AutoGenerated
	private VerticalLayout verticalLayout_3;

	@AutoGenerated
	private OptionGroup optionGroupCategories;

	@AutoGenerated
	private Panel panelAttributeParent;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private EncounterListView encounterListView;

	private static final long serialVersionUID = 1L;

	private AttributeParentType parentType;
	
	public AttributeOverviewView(AttributeParentType parentType) {
		this.parentType = parentType;
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
	
		if (parentType == AttributeParentType.SUBJECT) {
			verticalLayoutListWrapper.removeComponent(panelAttributeParent);
			panelAttributeCategories.setCaption("Subject Categories");
		}
		
		horizontalSplitPanel.setSplitPosition(20f, Unit.PERCENTAGE);
				
		optionGroupCategories.setMultiSelect(true);
		optionGroupCategories.setImmediate(true);
	}
	
	public AttributeParentType getParentType() {
		return parentType;
	}
	
	public void setAttributesPanelTitle(String title) {
		pnlAttributes.setCaption(title);
	}
	
	public void setCategoriesPanelTitle(String title) {
		panelAttributeCategories.setCaption(title);
	}

	public void addOptionGroupCategoriesValueChangeListener(ValueChangeListener listener) {
		optionGroupCategories.addValueChangeListener(listener);
	}
	
	public void addSaveListener(ClickListener listener) {
		btnSave.addClickListener(listener);
	}
	
	public void displayCategories(List<AttributeCategory> categories) {
		BeanItemContainer<AttributeCategory> c = new BeanItemContainer<AttributeCategory>(AttributeCategory.class);
		c.addAll(categories);
		optionGroupCategories.setContainerDataSource(c);
		optionGroupCategories.setItemCaptionPropertyId("label");
	}

	public void setSelectedCategories(List<AttributeCategory> chosenCategories) {
		optionGroupCategories.setValue(chosenCategories);
	}
	
	@SuppressWarnings("unchecked")
	public Collection<AttributeCategory> getChosenCategories() {
		return (Collection<AttributeCategory>)optionGroupCategories.getValue();
	}

	public EncounterListView getEncounterListView() {
		return encounterListView;
	}
	
	public void replaceAttributeEditor(Component editor) {
		verticalLayoutAttributes.removeAllComponents();
		verticalLayoutAttributes.addComponent(editor);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel
		horizontalSplitPanel = buildHorizontalSplitPanel();
		mainLayout.addComponent(horizontalSplitPanel);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel() {
		// common part: create layout
		horizontalSplitPanel = new HorizontalSplitPanel();
		horizontalSplitPanel.setImmediate(false);
		horizontalSplitPanel.setWidth("100.0%");
		horizontalSplitPanel.setHeight("100.0%");
		
		// verticalLayoutListWrapper
		verticalLayoutListWrapper = buildVerticalLayoutListWrapper();
		horizontalSplitPanel.addComponent(verticalLayoutListWrapper);
		
		// verticalLayoutPanelWrapper
		verticalLayoutPanelWrapper = buildVerticalLayoutPanelWrapper();
		horizontalSplitPanel.addComponent(verticalLayoutPanelWrapper);
		
		return horizontalSplitPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutListWrapper() {
		// common part: create layout
		verticalLayoutListWrapper = new VerticalLayout();
		verticalLayoutListWrapper.setImmediate(false);
		verticalLayoutListWrapper.setWidth("100.0%");
		verticalLayoutListWrapper.setHeight("100.0%");
		verticalLayoutListWrapper.setMargin(true);
		verticalLayoutListWrapper.setSpacing(true);
		
		// panelAttributeParent
		panelAttributeParent = buildPanelAttributeParent();
		verticalLayoutListWrapper.addComponent(panelAttributeParent);
		verticalLayoutListWrapper.setExpandRatio(panelAttributeParent, 1.0f);
		
		// panelAttributeCategories
		panelAttributeCategories = buildPanelAttributeCategories();
		verticalLayoutListWrapper.addComponent(panelAttributeCategories);
		verticalLayoutListWrapper
				.setExpandRatio(panelAttributeCategories, 1.0f);
		
		return verticalLayoutListWrapper;
	}

	@AutoGenerated
	private Panel buildPanelAttributeParent() {
		// common part: create layout
		panelAttributeParent = new Panel();
		panelAttributeParent.setCaption("Subject Encounters");
		panelAttributeParent.setImmediate(false);
		panelAttributeParent.setWidth("100.0%");
		panelAttributeParent.setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panelAttributeParent.setContent(verticalLayout_2);
		
		return panelAttributeParent;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(true);
		
		// encounterListView
		encounterListView = new EncounterListView();
		encounterListView.setImmediate(false);
		encounterListView.setWidth("100.0%");
		encounterListView.setHeight("100.0%");
		verticalLayout_2.addComponent(encounterListView);
		verticalLayout_2.setExpandRatio(encounterListView, 1.0f);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanelAttributeCategories() {
		// common part: create layout
		panelAttributeCategories = new Panel();
		panelAttributeCategories.setCaption("Encounter Categories");
		panelAttributeCategories.setImmediate(false);
		panelAttributeCategories.setWidth("100.0%");
		panelAttributeCategories.setHeight("100.0%");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panelAttributeCategories.setContent(verticalLayout_3);
		
		return panelAttributeCategories;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(true);
		
		// optionGroupCategories
		optionGroupCategories = new OptionGroup();
		optionGroupCategories.setImmediate(false);
		optionGroupCategories.setWidth("100.0%");
		optionGroupCategories.setHeight("100.0%");
		verticalLayout_3.addComponent(optionGroupCategories);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutPanelWrapper() {
		// common part: create layout
		verticalLayoutPanelWrapper = new VerticalLayout();
		verticalLayoutPanelWrapper.setImmediate(false);
		verticalLayoutPanelWrapper.setWidth("100.0%");
		verticalLayoutPanelWrapper.setHeight("100.0%");
		verticalLayoutPanelWrapper.setMargin(true);
		verticalLayoutPanelWrapper.setSpacing(true);
		
		// pnlAttributes
		pnlAttributes = buildPnlAttributes();
		verticalLayoutPanelWrapper.addComponent(pnlAttributes);
		verticalLayoutPanelWrapper.setExpandRatio(pnlAttributes, 1.0f);
		
		// horizontalLayoutButtons
		horizontalLayoutButtons = buildHorizontalLayoutButtons();
		verticalLayoutPanelWrapper.addComponent(horizontalLayoutButtons);
		verticalLayoutPanelWrapper.setComponentAlignment(
				horizontalLayoutButtons, new Alignment(34));
		
		return verticalLayoutPanelWrapper;
	}

	@AutoGenerated
	private Panel buildPnlAttributes() {
		// common part: create layout
		pnlAttributes = new Panel();
		pnlAttributes.setCaption("Attributes of XXX");
		pnlAttributes.setImmediate(false);
		pnlAttributes.setWidth("100.0%");
		pnlAttributes.setHeight("100.0%");
		
		// verticalLayoutAttributes
		verticalLayoutAttributes = new VerticalLayout();
		verticalLayoutAttributes.setImmediate(false);
		verticalLayoutAttributes.setWidth("100.0%");
		verticalLayoutAttributes.setHeight("100.0%");
		verticalLayoutAttributes.setMargin(true);
		verticalLayoutAttributes.setSpacing(true);
		pnlAttributes.setContent(verticalLayoutAttributes);
		
		return pnlAttributes;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutButtons() {
		// common part: create layout
		horizontalLayoutButtons = new HorizontalLayout();
		horizontalLayoutButtons.setImmediate(false);
		horizontalLayoutButtons.setWidth("-1px");
		horizontalLayoutButtons.setHeight("-1px");
		horizontalLayoutButtons.setMargin(false);
		horizontalLayoutButtons.setSpacing(true);
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Save");
		btnSave.setImmediate(true);
		btnSave.setWidth("80px");
		btnSave.setHeight("-1px");
		horizontalLayoutButtons.addComponent(btnSave);
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Cancel");
		btnCancel.setImmediate(true);
		btnCancel.setWidth("80px");
		btnCancel.setHeight("-1px");
		horizontalLayoutButtons.addComponent(btnCancel);
		
		return horizontalLayoutButtons;
	}

	public void setCategoriesPanelEnabled(boolean b) {
		panelAttributeCategories.setEnabled(b);
	}

	public void setAttributesPanelEnabled(boolean b) {
		pnlAttributes.setEnabled(b);
	}

}
