package eu.wuttke.nrf.ui.attribute;

import java.util.Arrays;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

import eu.wuttke.nrf.ui.visit.VisitListView;

public class AttributeOverviewView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel;
	@AutoGenerated
	private VerticalLayout verticalLayoutPanelWrapper;
	@AutoGenerated
	private HorizontalLayout horizontalLayoutButtons;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnSave;
	@AutoGenerated
	private Panel pnlAttributes;
	@AutoGenerated
	private VerticalLayout verticalLayoutAttributes;
	@AutoGenerated
	private VerticalLayout verticalLayoutListWrapper;
	@AutoGenerated
	private VisitListView visitListView;
	@AutoGenerated
	private OptionGroup optionGroup;
	public static final String SUBJECT_ATTRIBUTES = "Subject Attributes";
	public static final String VISIT_ATTRIBUTES = "Visit Attributes";
	
	public AttributeOverviewView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		horizontalSplitPanel.setSplitPosition(20f, Unit.PERCENTAGE);
		
		Container c = new IndexedContainer(Arrays.asList(new String[]{SUBJECT_ATTRIBUTES, VISIT_ATTRIBUTES}));
		optionGroup.setContainerDataSource(c);
		optionGroup.setValue(SUBJECT_ATTRIBUTES);
		optionGroup.setImmediate(true);
	}
	
	public void setAttributesPanelTitle(String title) {
		pnlAttributes.setCaption(title);
	}
	
	public void addOptionGroupValueChangeListener(ValueChangeListener listener) {
		optionGroup.addValueChangeListener(listener);
	}

	public boolean isShowSubjectAttributes() {
		return optionGroup.getValue() == SUBJECT_ATTRIBUTES;
	}

	public void setShowSubjectAttribute(boolean chosen) {
		optionGroup.setValue(chosen ? SUBJECT_ATTRIBUTES : VISIT_ATTRIBUTES);
	}

	public VisitListView getVisitListView() {
		return visitListView;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel
		horizontalSplitPanel = buildHorizontalSplitPanel();
		mainLayout.addComponent(horizontalSplitPanel);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel() {
		// common part: create layout
		horizontalSplitPanel = new HorizontalSplitPanel();
		horizontalSplitPanel.setImmediate(false);
		horizontalSplitPanel.setWidth("100.0%");
		horizontalSplitPanel.setHeight("100.0%");
		
		// verticalLayoutListWrapper
		verticalLayoutListWrapper = buildVerticalLayoutListWrapper();
		horizontalSplitPanel.addComponent(verticalLayoutListWrapper);
		
		// verticalLayoutPanelWrapper
		verticalLayoutPanelWrapper = buildVerticalLayoutPanelWrapper();
		horizontalSplitPanel.addComponent(verticalLayoutPanelWrapper);
		
		return horizontalSplitPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutListWrapper() {
		// common part: create layout
		verticalLayoutListWrapper = new VerticalLayout();
		verticalLayoutListWrapper.setImmediate(false);
		verticalLayoutListWrapper.setWidth("100.0%");
		verticalLayoutListWrapper.setHeight("100.0%");
		verticalLayoutListWrapper.setMargin(true);
		verticalLayoutListWrapper.setSpacing(true);
		
		// optionGroup
		optionGroup = new OptionGroup();
		optionGroup.setImmediate(false);
		optionGroup.setWidth("100.0%");
		optionGroup.setHeight("-1px");
		verticalLayoutListWrapper.addComponent(optionGroup);
		
		// visitListView
		visitListView = new VisitListView();
		visitListView.setImmediate(false);
		visitListView.setWidth("100.0%");
		visitListView.setHeight("100.0%");
		verticalLayoutListWrapper.addComponent(visitListView);
		verticalLayoutListWrapper.setExpandRatio(visitListView, 1.0f);
		
		return verticalLayoutListWrapper;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutPanelWrapper() {
		// common part: create layout
		verticalLayoutPanelWrapper = new VerticalLayout();
		verticalLayoutPanelWrapper.setImmediate(false);
		verticalLayoutPanelWrapper.setWidth("100.0%");
		verticalLayoutPanelWrapper.setHeight("100.0%");
		verticalLayoutPanelWrapper.setMargin(true);
		verticalLayoutPanelWrapper.setSpacing(true);
		
		// pnlAttributes
		pnlAttributes = buildPnlAttributes();
		verticalLayoutPanelWrapper.addComponent(pnlAttributes);
		verticalLayoutPanelWrapper.setExpandRatio(pnlAttributes, 1.0f);
		
		// horizontalLayoutButtons
		horizontalLayoutButtons = buildHorizontalLayoutButtons();
		verticalLayoutPanelWrapper.addComponent(horizontalLayoutButtons);
		verticalLayoutPanelWrapper.setComponentAlignment(
				horizontalLayoutButtons, new Alignment(34));
		
		return verticalLayoutPanelWrapper;
	}

	@AutoGenerated
	private Panel buildPnlAttributes() {
		// common part: create layout
		pnlAttributes = new Panel();
		pnlAttributes.setCaption("Attributes of XXX");
		pnlAttributes.setImmediate(false);
		pnlAttributes.setWidth("100.0%");
		pnlAttributes.setHeight("100.0%");
		
		// verticalLayoutAttributes
		verticalLayoutAttributes = new VerticalLayout();
		verticalLayoutAttributes.setImmediate(false);
		verticalLayoutAttributes.setWidth("100.0%");
		verticalLayoutAttributes.setHeight("100.0%");
		verticalLayoutAttributes.setMargin(false);
		pnlAttributes.setContent(verticalLayoutAttributes);
		
		return pnlAttributes;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutButtons() {
		// common part: create layout
		horizontalLayoutButtons = new HorizontalLayout();
		horizontalLayoutButtons.setImmediate(false);
		horizontalLayoutButtons.setWidth("-1px");
		horizontalLayoutButtons.setHeight("-1px");
		horizontalLayoutButtons.setMargin(false);
		horizontalLayoutButtons.setSpacing(true);
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Save");
		btnSave.setImmediate(false);
		btnSave.setWidth("80px");
		btnSave.setHeight("-1px");
		horizontalLayoutButtons.addComponent(btnSave);
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Cancel");
		btnCancel.setImmediate(false);
		btnCancel.setWidth("80px");
		btnCancel.setHeight("-1px");
		horizontalLayoutButtons.addComponent(btnCancel);
		
		return horizontalLayoutButtons;
	}

}
