package eu.wuttke.nrf.ui.medication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.PropertyId;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import eu.wuttke.nrf.domain.medication.Medication;
import eu.wuttke.nrf.ui.misc.StringToPrecisionDateConverter;
import eu.wuttke.nrf.ui.view.EditorView;

public class MedicationEditorView 
extends CustomComponent
implements EditorView<Medication> {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private FormLayout formLayout;
	@AutoGenerated
	@PropertyId("validUntil")
	private TextField tfValidUntil;
	@AutoGenerated
	@PropertyId("validFrom")
	private TextField tfValidFrom;
	@AutoGenerated
	@PropertyId("description")
	private TextArea taDescription;
	@AutoGenerated
	private Label lblAtcCode;
	@AutoGenerated
	private Label lblPharmaceuticalForm;
	@AutoGenerated
	@PropertyId("amount")
	private TextField tfAmount;
	@AutoGenerated
	private HorizontalLayout horizontalLayoutCode;
	@AutoGenerated
	private Button btnChooseCode;
	@AutoGenerated
	private Label lblMedication;
	private static final long serialVersionUID = 1L;
	
	private BeanItem<Medication> beanItem;
	private FieldGroup group;

	public MedicationEditorView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		tfValidFrom.setConverter(new StringToPrecisionDateConverter());
		tfValidUntil.setConverter(new StringToPrecisionDateConverter());
	}
	
	@Override
	public void displayEntity(Medication d) {
		beanItem = new BeanItem<Medication>(d);
		group = new FieldGroup(beanItem);
		group.bindMemberFields(this);
	}

	public void displayAtcCode(String text) {
		lblAtcCode.setValue(text);
	}

	public void displayMedicament(String text) {
		lblMedication.setValue(text);
	}
	
	public void displayPharmaceuticalForm(String text) {
		lblPharmaceuticalForm.setValue(text);
	}

	@Override
	public Medication retrieveValidatedEntity() {
		try {
			group.commit();
			return beanItem.getBean();
		} catch (CommitException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	public void addChooseListener(ClickListener cl) {
		btnChooseCode.addClickListener(cl);
	}

	@Override
	public boolean isValid() {
		return group.isValid();
	}
	
	public void addChooseCodeClickListener(ClickListener listener) {
		btnChooseCode.addClickListener(listener);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// formLayout
		formLayout = buildFormLayout();
		mainLayout.addComponent(formLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private FormLayout buildFormLayout() {
		// common part: create layout
		formLayout = new FormLayout();
		formLayout.setImmediate(false);
		formLayout.setWidth("100.0%");
		formLayout.setHeight("100.0%");
		formLayout.setMargin(false);
		formLayout.setSpacing(true);
		
		// horizontalLayoutCode
		horizontalLayoutCode = buildHorizontalLayoutCode();
		formLayout.addComponent(horizontalLayoutCode);
		formLayout.setComponentAlignment(horizontalLayoutCode,
				new Alignment(20));
		
		// tfAmount
		tfAmount = new TextField();
		tfAmount.setCaption("Amount");
		tfAmount.setImmediate(false);
		tfAmount.setWidth("100.0%");
		tfAmount.setHeight("-1px");
		tfAmount.setRequired(false);
		formLayout.addComponent(tfAmount);
		
		// lblPharmaceuticalForm
		lblPharmaceuticalForm = new Label();
		lblPharmaceuticalForm.setCaption("Pharmaceutical Form");
		lblPharmaceuticalForm.setImmediate(false);
		lblPharmaceuticalForm.setWidth("-1px");
		lblPharmaceuticalForm.setHeight("-1px");
		formLayout.addComponent(lblPharmaceuticalForm);
		
		// lblAtcCode
		lblAtcCode = new Label();
		lblAtcCode.setCaption("ATC Code");
		lblAtcCode.setImmediate(false);
		lblAtcCode.setWidth("-1px");
		lblAtcCode.setHeight("-1px");
		formLayout.addComponent(lblAtcCode);
		
		// taDescription
		taDescription = new TextArea();
		taDescription.setCaption("Description");
		taDescription.setImmediate(false);
		taDescription.setWidth("100.0%");
		taDescription.setHeight("100.0%");
		taDescription.setNullRepresentation("");
		formLayout.addComponent(taDescription);
		formLayout.setExpandRatio(taDescription, 1.0f);
		
		// tfValidFrom
		tfValidFrom = new TextField();
		tfValidFrom.setCaption("Valid From");
		tfValidFrom.setImmediate(true);
		tfValidFrom.setWidth("100.0%");
		tfValidFrom.setHeight("-1px");
		formLayout.addComponent(tfValidFrom);
		
		// tfValidUntil
		tfValidUntil = new TextField();
		tfValidUntil.setCaption("Valid Until");
		tfValidUntil.setImmediate(true);
		tfValidUntil.setWidth("100.0%");
		tfValidUntil.setHeight("-1px");
		formLayout.addComponent(tfValidUntil);
		
		return formLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutCode() {
		// common part: create layout
		horizontalLayoutCode = new HorizontalLayout();
		horizontalLayoutCode.setCaption("Medication");
		horizontalLayoutCode.setImmediate(false);
		horizontalLayoutCode.setWidth("100.0%");
		horizontalLayoutCode.setHeight("-1px");
		horizontalLayoutCode.setMargin(false);
		horizontalLayoutCode.setSpacing(true);
		
		// lblMedication
		lblMedication = new Label();
		lblMedication.setImmediate(false);
		lblMedication.setWidth("100.0%");
		lblMedication.setHeight("-1px");
		horizontalLayoutCode.addComponent(lblMedication);
		horizontalLayoutCode.setComponentAlignment(lblMedication,
				new Alignment(33));
		
		// btnChooseCode
		btnChooseCode = new Button();
		btnChooseCode.setCaption("Choose");
		btnChooseCode.setImmediate(true);
		btnChooseCode.setWidth("-1px");
		btnChooseCode.setHeight("-1px");
		horizontalLayoutCode.addComponent(btnChooseCode);
		
		return horizontalLayoutCode;
	}

}
