// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.diagnosis;

import eu.wuttke.nrf.domain.diagnosis.Icd10Code;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Icd10Code_Roo_Configurable {
    
    declare @type: Icd10Code: @Configurable;
    
}
