// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.nrf.domain.diagnosis;

import eu.wuttke.nrf.domain.diagnosis.Icd10Code;
import javax.persistence.Entity;

privileged aspect Icd10Code_Roo_Jpa_Entity {
    
    declare @type: Icd10Code: @Entity;
    
}
